<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NVHA" name="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS" tests="7" failures="1" timestamp="29 Nov 2017 09:23:57 GMT" time="298.476" errors="0">
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_7" time="46.625" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_4" time="30.182" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1" time="61.747" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS">
    <failure type="java.lang.AssertionError" message="Tiếp nhận Bệnh nhân không thành công !">
      <![CDATA[java.lang.AssertionError: Tiếp nhận Bệnh nhân không thành công !
	at org.testng.Assert.fail(Assert.java:94)
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1(TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1 -->
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_2" time="93.034" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_5" time="16.115" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_6" time="18.674" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_3" time="32.099" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
</testsuite> <!-- TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS -->
