<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NVHA" name="TestHIS.TestLuongDichVu_13767" tests="7" failures="1" timestamp="5 Dec 2017 09:09:31 GMT" time="311.330" errors="0">
  <testcase name="DichVu_13767_3" time="31.694" classname="TestHIS.TestLuongDichVu_13767"/>
  <testcase name="DichVu_13767_6" time="18.898" classname="TestHIS.TestLuongDichVu_13767"/>
  <testcase name="DichVu_13767_5" time="16.225" classname="TestHIS.TestLuongDichVu_13767"/>
  <testcase name="DichVu_13767_7" time="59.602" classname="TestHIS.TestLuongDichVu_13767"/>
  <testcase name="DichVu_13767_2" time="93.889" classname="TestHIS.TestLuongDichVu_13767"/>
  <testcase name="DichVu_13767_4" time="28.836" classname="TestHIS.TestLuongDichVu_13767"/>
  <testcase name="DichVu_13767_1" time="62.186" classname="TestHIS.TestLuongDichVu_13767">
    <failure type="java.lang.AssertionError" message="Tiếp nhận Bệnh nhân không thành công !">
      <![CDATA[java.lang.AssertionError: Tiếp nhận Bệnh nhân không thành công !
	at org.testng.Assert.fail(Assert.java:94)
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:520)
	at TestHIS.TestLuongDichVu_13767.DichVu_13767_1(TestLuongDichVu_13767.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- DichVu_13767_1 -->
</testsuite> <!-- TestHIS.TestLuongDichVu_13767 -->
