<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NVHA" name="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS" tests="7" failures="1" timestamp="29 Nov 2017 09:46:16 GMT" time="296.680" errors="0">
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1" time="62.108" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS">
    <failure type="java.lang.AssertionError" message="Tiếp nhận Bệnh nhân không thành công !">
      <![CDATA[java.lang.AssertionError: Tiếp nhận Bệnh nhân không thành công !
	at org.testng.Assert.fail(Assert.java:94)
	at desktop_Framework.CommonActions.setTestcaseStatus(CommonActions.java:542)
	at TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS.TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1(TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_1 -->
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_5" time="16.132" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_6" time="18.740" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_4" time="29.419" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_2" time="92.452" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_3" time="32.063" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
  <testcase name="TestLuongTiepNhanBenhNhanDichVu_ThuTienSau_7" time="45.766" classname="TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS"/>
</testsuite> <!-- TestHIS.TestLuongTiepNhanBNDichVu_ThuTienSau_KhongCLS -->
